from typing import Protocol, Iterator

class LLMBackend(Protocol):
    def complete(self, messages: list[dict], tools: list[dict] = []): ...
    def chat(self, messages: list[dict], tools: list[dict] = []) -> Iterator[str]: ...
